DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(20),
  lastname VARCHAR(40),
  code VARCHAR(40) UNIQUE
);

DROP TABLE IF EXISTS GRUPO;
CREATE TABLE GRUPO (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(20) UNIQUE
);


CREATE TABLE USUARIO_GRUPO (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_usuario INT,
  id_grupo INT,
  FOREIGN KEY (id_usuario) REFERENCES USUARIO(id),
  FOREIGN KEY (id_grupo) REFERENCES GRUPO(id)
);

