INSERT INTO USUARIO ("ID", "USERNAME", "LASTNAME", "CODE") VALUES(1, 'USERNAME1', 'LASTNAME1', 'CODE1');
INSERT INTO USUARIO ("ID", "USERNAME", "LASTNAME", "CODE") VALUES(2, 'USERNAME2', 'LASTNAME2', 'CODE2');

INSERT INTO GRUPO("ID", "NOMBRE") VALUES(1, 'GRUPO01');
INSERT INTO GRUPO("ID", "NOMBRE") VALUES(2, 'GRUPO02');

INSERT INTO USUARIO_GRUPO("ID_USUARIO", "ID_GRUPO") VALUES(1, 1);
INSERT INTO USUARIO_GRUPO("ID_USUARIO", "ID_GRUPO") VALUES(1, 2);